INSERT INTO public.answer (id_question, text_answer) VALUES (8, 'Сайт приюта для бездомных животных был создан волонтерами на добровольной основе');
INSERT INTO public.answer (id_question, text_answer) VALUES (8, 'Наша цель − помощь животным приюта и привлечение внимания к проблемам бездомных животных в целом');
INSERT INTO public.answer (id_question, text_answer) VALUES (8, 'Конечно, в первую очередь, мы хотим помочь обрести нашим подопечным свой дом и хозяев.');
INSERT INTO public.answer (id_question, text_answer) VALUES (9, 'Приют находится в г. Москве, район Печатники, промышленная зона Курьяново.');
INSERT INTO public.answer (id_question, text_answer) VALUES (9, 'Если вы хотите посетить наш приют, в частности, привезти собакам и кошкам корм, лекарства, наполнители и/или любую другую помощь, познакомиться с тем или иным питомцем, просим вас:');
INSERT INTO public.answer (id_question, text_answer) VALUES (9, 'Звоните нам по телефонам указанным в разделе "Контактные данные для связи" и мы сообщим вам точный адрес приюта и как лучше добраться.');
INSERT INTO public.answer (id_question, text_answer) VALUES (9, 'Контактные данные для связи: 8 (916) 530-64-94 (Ирина); 8 (903) 973-03-59 (Татьяна Никандровна); 8 (977) 724 30 82 Пётр Николаевич; Кошки: 8 (916) 210-10-44 (Виктория).');
INSERT INTO public.answer (id_question, text_answer) VALUES (9, 'Схема проезда в приют на машине');
INSERT INTO public.answer (id_question, text_answer) VALUES (9, 'Схема проезда в приют на общественном транспорте');
INSERT INTO public.answer (id_question, text_answer) VALUES (9, 'Схема проезда в приют на машине');
INSERT INTO public.answer (id_question, text_answer) VALUES (10, 'Контактные данные охраны для оформления пропуска на машину.');
INSERT INTO public.answer (id_question, text_answer) VALUES (10, 'Схема проезда на КПП2 для оформления пропуска');
INSERT INTO public.answer (id_question, text_answer) VALUES (11, 'Общие рекомендации о технике безопасности на территории приюта.');
INSERT INTO public.answer (id_question, text_answer) VALUES (14, 'Правила знакомства с животным до того, как забрать его из приюта');
INSERT INTO public.answer (id_question, text_answer) VALUES (15, 'Если Вы приняли решение взять питомца, тогда звоните волонтеру понравившейся собаки и приезжаете к нам, имея на руках паспорт. Заполняется договор передачи.');
INSERT INTO public.answer (id_question, text_answer) VALUES (15, 'Мы проверяем серьезность Ваших намерений, задаем вопросы. У нас есть критерии к людям, забирающим животное. Отдаем только в хорошие руки.');
INSERT INTO public.answer (id_question, text_answer) VALUES (16, 'Список рекомендаций по транспортировке животного. Волонтер вместе с Вами, чтобы у собаки не было стресса, отвозит животное к Вам домой. Помогает помыть ее и освоиться на новом месте.');
INSERT INTO public.answer (id_question, text_answer) VALUES (17, 'Список рекомендаций по обустройству дома для щенка/котенка.');
INSERT INTO public.answer (id_question, text_answer) VALUES (18, 'Список рекомендаций по обустройству дома для взрослого животного.');
INSERT INTO public.answer (id_question, text_answer) VALUES (19, 'Список рекомендаций по обустройству дома для животного с ограниченными возможностями.');
INSERT INTO public.answer (id_question, text_answer) VALUES (20, 'Советы кинолога по первичному общению с собакой. Правило первое - Разговаривайте со своей собакой');
INSERT INTO public.answer (id_question, text_answer) VALUES (20, 'Правило второеое - Следите за своими эмоциями. Быть членом общества — это значит уметь чутко реагировать на сигналы других членов своей группы и адекватно отвечать им.');
INSERT INTO public.answer (id_question, text_answer) VALUES (21, 'Рекомендации по проверенным кинологам. Ниже указанны координаты и опыт работы кинологов, к которым мы рекомендуем обращаться:');
INSERT INTO public.answer (id_question, text_answer) VALUES (21, 'Кинолог с опытом работы 10 лет. Иванов Иван Иванович. e-mail: ivanov@yandex.ru');
INSERT INTO public.answer (id_question, text_answer) VALUES (22, 'Список причин отказа в заборе животного из приюта.');
